openapi: "3.0.0"
info:
  version: 1.0.0
  title: Profile Service

servers:
  - url: http://some-domain/api
paths:
  /profile/{name}:
    get:
      summary: Get profile details(age, gender, nationality) from a givin name
      description: |
        This API Return age, gender, nationality from a givin name.
        The name is passed from the path variable. Any input are accepted yet not all names are with full information.
        The age, gender, nationality are got from agify.io, genderize.io, nationalize.io.
        The downstream may return null information on a given name.
        In this case, this API will return null on the corresponding information as well.
        The nationalize.io will return a list of possible ISO 3166-1 alpha-2 country code order by probability. This api will return the first record from there.
      parameters:
              - in: path
                name: name
                schema:
                  type: string
                required: true
                description: The name of the profile
      responses:
        200:
          description: Check accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDetails'
        404:
          description: Not found
        500:
          description: Internal server error


components:
  schemas:
    ProfileDetails:
      type: object
      properties:
        age:
          type: integer
          description: value from agify.io
        gender:
          type: string
          description: male or femail from genderize.io
        nationality:
          type: string
          description: The nationalize.io will return a list of possible ISO 3166-1 alpha-2 country code order by probability. This propertiy is the first record from there.

